FROM node:18-alpine as builder

WORKDIR /usr/src/app
COPY package.json ./

ARG NEXT_PUBLIC_CALL_SOCKET
ARG NEXT_PUBLIC_CHAT_SOCKET
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_HOST

ENV NEXT_PUBLIC_CALL_SOCKET=$NEXT_PUBLIC_CALL_SOCKET
ENV NEXT_PUBLIC_CHAT_SOCKET=$NEXT_PUBLIC_CHAT_SOCKET
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_HOST=$NEXT_PUBLIC_HOST

RUN yarn install --network-concurrency 1 --ignore-scripts --frozen-lockfile
COPY . ./

RUN yarn build 

EXPOSE 5000
CMD ["yarn", "start"]

