export enum FriendType {
  NOT_FRIEND = 'NOT_FRIEND',
  REQUESTING = 'REQUESTING',
  BE_REQUESTED = 'BE_REQUESTED',
  BE_FRIEND = 'BE_FRIEND',
}

export enum FriendTabs {
  ALL_FRIENDS = 'ALL_FRIENDS',
  FRIEND_SUGGESTIONS = 'FRIEND_SUGGESTIONS',
  FRIEND_REQUESTS = 'FRIEND_REQUESTS',
}
