name: Deploy Auth Service

on:
  push:
    branches: ['dev']

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: vtri/sim-fri-client
      DIGITAL_ACCESS_TOKEN: ${{ secrets.DIGITAL_ACCESS_TOKEN }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      DEPLOYMENT_NAME: sim-fri-client

    steps:
      - uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig Staging
        run: doctl kubernetes cluster kubeconfig save $CLUSTER_NAME

      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build image
        run: docker build . -t $IMAGE_NAME --build-arg NEXT_PUBLIC_CALL_SOCKET=ws://167.172.5.183/call --build-arg NEXT_PUBLIC_CHAT_SOCKET=ws://167.172.5.183/chat --build-arg NEXT_PUBLIC_BASE_URL=http://167.172.5.183/api --build-arg NEXT_PUBLIC_HOST=http://167.172.5.183

      - name: Push to Docker hub
        run: docker push $IMAGE_NAME

      - name: Kubernetes rollout the latest image
        run: kubectl rollout restart deployment $DEPLOYMENT_NAME
